// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gsbn.proto

#ifndef PROTOBUF_gsbn_2eproto__INCLUDED
#define PROTOBUF_gsbn_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gsbn {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gsbn_2eproto();
void protobuf_AssignDesc_gsbn_2eproto();
void protobuf_ShutdownFile_gsbn_2eproto();

class SolverParam;
class GenParam;
class ModeParam;
class NetParam;
class PopParam;
class HcuParam;
class McuParam;
class ProjParam;
class SolverState;
class TableState;
class StimRawData;

// ===================================================================

class SolverParam : public ::google::protobuf::Message {
 public:
  SolverParam();
  virtual ~SolverParam();

  SolverParam(const SolverParam& from);

  inline SolverParam& operator=(const SolverParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SolverParam& default_instance();

  void Swap(SolverParam* other);

  // implements Message ----------------------------------------------

  SolverParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SolverParam& from);
  void MergeFrom(const SolverParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .gsbn.GenParam gen_param = 1;
  inline bool has_gen_param() const;
  inline void clear_gen_param();
  static const int kGenParamFieldNumber = 1;
  inline const ::gsbn::GenParam& gen_param() const;
  inline ::gsbn::GenParam* mutable_gen_param();
  inline ::gsbn::GenParam* release_gen_param();
  inline void set_allocated_gen_param(::gsbn::GenParam* gen_param);

  // required .gsbn.NetParam net_param = 2;
  inline bool has_net_param() const;
  inline void clear_net_param();
  static const int kNetParamFieldNumber = 2;
  inline const ::gsbn::NetParam& net_param() const;
  inline ::gsbn::NetParam* mutable_net_param();
  inline ::gsbn::NetParam* release_net_param();
  inline void set_allocated_net_param(::gsbn::NetParam* net_param);

  // @@protoc_insertion_point(class_scope:gsbn.SolverParam)
 private:
  inline void set_has_gen_param();
  inline void clear_has_gen_param();
  inline void set_has_net_param();
  inline void clear_has_net_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::gsbn::GenParam* gen_param_;
  ::gsbn::NetParam* net_param_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static SolverParam* default_instance_;
};
// -------------------------------------------------------------------

class GenParam : public ::google::protobuf::Message {
 public:
  GenParam();
  virtual ~GenParam();

  GenParam(const GenParam& from);

  inline GenParam& operator=(const GenParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GenParam& default_instance();

  void Swap(GenParam* other);

  // implements Message ----------------------------------------------

  GenParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GenParam& from);
  void MergeFrom(const GenParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string stim_file = 1;
  inline bool has_stim_file() const;
  inline void clear_stim_file();
  static const int kStimFileFieldNumber = 1;
  inline const ::std::string& stim_file() const;
  inline void set_stim_file(const ::std::string& value);
  inline void set_stim_file(const char* value);
  inline void set_stim_file(const char* value, size_t size);
  inline ::std::string* mutable_stim_file();
  inline ::std::string* release_stim_file();
  inline void set_allocated_stim_file(::std::string* stim_file);

  // required float dt = 2;
  inline bool has_dt() const;
  inline void clear_dt();
  static const int kDtFieldNumber = 2;
  inline float dt() const;
  inline void set_dt(float value);

  // repeated .gsbn.ModeParam mode_param = 3;
  inline int mode_param_size() const;
  inline void clear_mode_param();
  static const int kModeParamFieldNumber = 3;
  inline const ::gsbn::ModeParam& mode_param(int index) const;
  inline ::gsbn::ModeParam* mutable_mode_param(int index);
  inline ::gsbn::ModeParam* add_mode_param();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::ModeParam >&
      mode_param() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::ModeParam >*
      mutable_mode_param();

  // @@protoc_insertion_point(class_scope:gsbn.GenParam)
 private:
  inline void set_has_stim_file();
  inline void clear_has_stim_file();
  inline void set_has_dt();
  inline void clear_has_dt();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* stim_file_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::ModeParam > mode_param_;
  float dt_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static GenParam* default_instance_;
};
// -------------------------------------------------------------------

class ModeParam : public ::google::protobuf::Message {
 public:
  ModeParam();
  virtual ~ModeParam();

  ModeParam(const ModeParam& from);

  inline ModeParam& operator=(const ModeParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModeParam& default_instance();

  void Swap(ModeParam* other);

  // implements Message ----------------------------------------------

  ModeParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ModeParam& from);
  void MergeFrom(const ModeParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float begin_time = 1;
  inline bool has_begin_time() const;
  inline void clear_begin_time();
  static const int kBeginTimeFieldNumber = 1;
  inline float begin_time() const;
  inline void set_begin_time(float value);

  // required float end_time = 2;
  inline bool has_end_time() const;
  inline void clear_end_time();
  static const int kEndTimeFieldNumber = 2;
  inline float end_time() const;
  inline void set_end_time(float value);

  // optional float prn = 3 [default = 1];
  inline bool has_prn() const;
  inline void clear_prn();
  static const int kPrnFieldNumber = 3;
  inline float prn() const;
  inline void set_prn(float value);

  // optional float gain_mask = 4 [default = 1];
  inline bool has_gain_mask() const;
  inline void clear_gain_mask();
  static const int kGainMaskFieldNumber = 4;
  inline float gain_mask() const;
  inline void set_gain_mask(float value);

  // optional uint32 plasticity = 5 [default = 1];
  inline bool has_plasticity() const;
  inline void clear_plasticity();
  static const int kPlasticityFieldNumber = 5;
  inline ::google::protobuf::uint32 plasticity() const;
  inline void set_plasticity(::google::protobuf::uint32 value);

  // optional uint32 stim_index = 6 [default = 0];
  inline bool has_stim_index() const;
  inline void clear_stim_index();
  static const int kStimIndexFieldNumber = 6;
  inline ::google::protobuf::uint32 stim_index() const;
  inline void set_stim_index(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gsbn.ModeParam)
 private:
  inline void set_has_begin_time();
  inline void clear_has_begin_time();
  inline void set_has_end_time();
  inline void clear_has_end_time();
  inline void set_has_prn();
  inline void clear_has_prn();
  inline void set_has_gain_mask();
  inline void clear_has_gain_mask();
  inline void set_has_plasticity();
  inline void clear_has_plasticity();
  inline void set_has_stim_index();
  inline void clear_has_stim_index();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float begin_time_;
  float end_time_;
  float prn_;
  float gain_mask_;
  ::google::protobuf::uint32 plasticity_;
  ::google::protobuf::uint32 stim_index_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static ModeParam* default_instance_;
};
// -------------------------------------------------------------------

class NetParam : public ::google::protobuf::Message {
 public:
  NetParam();
  virtual ~NetParam();

  NetParam(const NetParam& from);

  inline NetParam& operator=(const NetParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const NetParam& default_instance();

  void Swap(NetParam* other);

  // implements Message ----------------------------------------------

  NetParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NetParam& from);
  void MergeFrom(const NetParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gsbn.PopParam pop_param = 1;
  inline int pop_param_size() const;
  inline void clear_pop_param();
  static const int kPopParamFieldNumber = 1;
  inline const ::gsbn::PopParam& pop_param(int index) const;
  inline ::gsbn::PopParam* mutable_pop_param(int index);
  inline ::gsbn::PopParam* add_pop_param();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::PopParam >&
      pop_param() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::PopParam >*
      mutable_pop_param();

  // repeated .gsbn.ProjParam proj_param = 2;
  inline int proj_param_size() const;
  inline void clear_proj_param();
  static const int kProjParamFieldNumber = 2;
  inline const ::gsbn::ProjParam& proj_param(int index) const;
  inline ::gsbn::ProjParam* mutable_proj_param(int index);
  inline ::gsbn::ProjParam* add_proj_param();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::ProjParam >&
      proj_param() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::ProjParam >*
      mutable_proj_param();

  // @@protoc_insertion_point(class_scope:gsbn.NetParam)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::PopParam > pop_param_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::ProjParam > proj_param_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static NetParam* default_instance_;
};
// -------------------------------------------------------------------

class PopParam : public ::google::protobuf::Message {
 public:
  PopParam();
  virtual ~PopParam();

  PopParam(const PopParam& from);

  inline PopParam& operator=(const PopParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PopParam& default_instance();

  void Swap(PopParam* other);

  // implements Message ----------------------------------------------

  PopParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PopParam& from);
  void MergeFrom(const PopParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 pop_num = 1;
  inline bool has_pop_num() const;
  inline void clear_pop_num();
  static const int kPopNumFieldNumber = 1;
  inline ::google::protobuf::uint32 pop_num() const;
  inline void set_pop_num(::google::protobuf::uint32 value);

  // repeated .gsbn.HcuParam hcu_param = 2;
  inline int hcu_param_size() const;
  inline void clear_hcu_param();
  static const int kHcuParamFieldNumber = 2;
  inline const ::gsbn::HcuParam& hcu_param(int index) const;
  inline ::gsbn::HcuParam* mutable_hcu_param(int index);
  inline ::gsbn::HcuParam* add_hcu_param();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::HcuParam >&
      hcu_param() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::HcuParam >*
      mutable_hcu_param();

  // @@protoc_insertion_point(class_scope:gsbn.PopParam)
 private:
  inline void set_has_pop_num();
  inline void clear_has_pop_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::HcuParam > hcu_param_;
  ::google::protobuf::uint32 pop_num_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static PopParam* default_instance_;
};
// -------------------------------------------------------------------

class HcuParam : public ::google::protobuf::Message {
 public:
  HcuParam();
  virtual ~HcuParam();

  HcuParam(const HcuParam& from);

  inline HcuParam& operator=(const HcuParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HcuParam& default_instance();

  void Swap(HcuParam* other);

  // implements Message ----------------------------------------------

  HcuParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HcuParam& from);
  void MergeFrom(const HcuParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 hcu_num = 1;
  inline bool has_hcu_num() const;
  inline void clear_hcu_num();
  static const int kHcuNumFieldNumber = 1;
  inline ::google::protobuf::uint32 hcu_num() const;
  inline void set_hcu_num(::google::protobuf::uint32 value);

  // required uint32 slot_num = 2;
  inline bool has_slot_num() const;
  inline void clear_slot_num();
  static const int kSlotNumFieldNumber = 2;
  inline ::google::protobuf::uint32 slot_num() const;
  inline void set_slot_num(::google::protobuf::uint32 value);

  // repeated .gsbn.McuParam mcu_param = 3;
  inline int mcu_param_size() const;
  inline void clear_mcu_param();
  static const int kMcuParamFieldNumber = 3;
  inline const ::gsbn::McuParam& mcu_param(int index) const;
  inline ::gsbn::McuParam* mutable_mcu_param(int index);
  inline ::gsbn::McuParam* add_mcu_param();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::McuParam >&
      mcu_param() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::McuParam >*
      mutable_mcu_param();

  // required float taum = 4;
  inline bool has_taum() const;
  inline void clear_taum();
  static const int kTaumFieldNumber = 4;
  inline float taum() const;
  inline void set_taum(float value);

  // required float wtagain = 5;
  inline bool has_wtagain() const;
  inline void clear_wtagain();
  static const int kWtagainFieldNumber = 5;
  inline float wtagain() const;
  inline void set_wtagain(float value);

  // required float maxfq = 6;
  inline bool has_maxfq() const;
  inline void clear_maxfq();
  static const int kMaxfqFieldNumber = 6;
  inline float maxfq() const;
  inline void set_maxfq(float value);

  // optional float igain = 7 [default = 1];
  inline bool has_igain() const;
  inline void clear_igain();
  static const int kIgainFieldNumber = 7;
  inline float igain() const;
  inline void set_igain(float value);

  // optional float wgain = 8 [default = 1];
  inline bool has_wgain() const;
  inline void clear_wgain();
  static const int kWgainFieldNumber = 8;
  inline float wgain() const;
  inline void set_wgain(float value);

  // optional float snoise = 9 [default = 0];
  inline bool has_snoise() const;
  inline void clear_snoise();
  static const int kSnoiseFieldNumber = 9;
  inline float snoise() const;
  inline void set_snoise(float value);

  // optional float lgbias = 10 [default = 0];
  inline bool has_lgbias() const;
  inline void clear_lgbias();
  static const int kLgbiasFieldNumber = 10;
  inline float lgbias() const;
  inline void set_lgbias(float value);

  // @@protoc_insertion_point(class_scope:gsbn.HcuParam)
 private:
  inline void set_has_hcu_num();
  inline void clear_has_hcu_num();
  inline void set_has_slot_num();
  inline void clear_has_slot_num();
  inline void set_has_taum();
  inline void clear_has_taum();
  inline void set_has_wtagain();
  inline void clear_has_wtagain();
  inline void set_has_maxfq();
  inline void clear_has_maxfq();
  inline void set_has_igain();
  inline void clear_has_igain();
  inline void set_has_wgain();
  inline void clear_has_wgain();
  inline void set_has_snoise();
  inline void clear_has_snoise();
  inline void set_has_lgbias();
  inline void clear_has_lgbias();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 hcu_num_;
  ::google::protobuf::uint32 slot_num_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::McuParam > mcu_param_;
  float taum_;
  float wtagain_;
  float maxfq_;
  float igain_;
  float wgain_;
  float snoise_;
  float lgbias_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static HcuParam* default_instance_;
};
// -------------------------------------------------------------------

class McuParam : public ::google::protobuf::Message {
 public:
  McuParam();
  virtual ~McuParam();

  McuParam(const McuParam& from);

  inline McuParam& operator=(const McuParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const McuParam& default_instance();

  void Swap(McuParam* other);

  // implements Message ----------------------------------------------

  McuParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const McuParam& from);
  void MergeFrom(const McuParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 mcu_num = 1;
  inline bool has_mcu_num() const;
  inline void clear_mcu_num();
  static const int kMcuNumFieldNumber = 1;
  inline ::google::protobuf::uint32 mcu_num() const;
  inline void set_mcu_num(::google::protobuf::uint32 value);

  // required uint32 fanout_num = 2;
  inline bool has_fanout_num() const;
  inline void clear_fanout_num();
  static const int kFanoutNumFieldNumber = 2;
  inline ::google::protobuf::uint32 fanout_num() const;
  inline void set_fanout_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gsbn.McuParam)
 private:
  inline void set_has_mcu_num();
  inline void clear_has_mcu_num();
  inline void set_has_fanout_num();
  inline void clear_has_fanout_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 mcu_num_;
  ::google::protobuf::uint32 fanout_num_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static McuParam* default_instance_;
};
// -------------------------------------------------------------------

class ProjParam : public ::google::protobuf::Message {
 public:
  ProjParam();
  virtual ~ProjParam();

  ProjParam(const ProjParam& from);

  inline ProjParam& operator=(const ProjParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProjParam& default_instance();

  void Swap(ProjParam* other);

  // implements Message ----------------------------------------------

  ProjParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProjParam& from);
  void MergeFrom(const ProjParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 src_pop = 1;
  inline bool has_src_pop() const;
  inline void clear_src_pop();
  static const int kSrcPopFieldNumber = 1;
  inline ::google::protobuf::uint32 src_pop() const;
  inline void set_src_pop(::google::protobuf::uint32 value);

  // required uint32 dest_pop = 2;
  inline bool has_dest_pop() const;
  inline void clear_dest_pop();
  static const int kDestPopFieldNumber = 2;
  inline ::google::protobuf::uint32 dest_pop() const;
  inline void set_dest_pop(::google::protobuf::uint32 value);

  // required float tauzi = 3;
  inline bool has_tauzi() const;
  inline void clear_tauzi();
  static const int kTauziFieldNumber = 3;
  inline float tauzi() const;
  inline void set_tauzi(float value);

  // required float tauzj = 4;
  inline bool has_tauzj() const;
  inline void clear_tauzj();
  static const int kTauzjFieldNumber = 4;
  inline float tauzj() const;
  inline void set_tauzj(float value);

  // required float taue = 5;
  inline bool has_taue() const;
  inline void clear_taue();
  static const int kTaueFieldNumber = 5;
  inline float taue() const;
  inline void set_taue(float value);

  // required float taup = 6;
  inline bool has_taup() const;
  inline void clear_taup();
  static const int kTaupFieldNumber = 6;
  inline float taup() const;
  inline void set_taup(float value);

  // required float maxfq = 7;
  inline bool has_maxfq() const;
  inline void clear_maxfq();
  static const int kMaxfqFieldNumber = 7;
  inline float maxfq() const;
  inline void set_maxfq(float value);

  // optional float bgain = 8 [default = 0];
  inline bool has_bgain() const;
  inline void clear_bgain();
  static const int kBgainFieldNumber = 8;
  inline float bgain() const;
  inline void set_bgain(float value);

  // optional float wgain = 9 [default = 0];
  inline bool has_wgain() const;
  inline void clear_wgain();
  static const int kWgainFieldNumber = 9;
  inline float wgain() const;
  inline void set_wgain(float value);

  // optional float pi0 = 10 [default = 0];
  inline bool has_pi0() const;
  inline void clear_pi0();
  static const int kPi0FieldNumber = 10;
  inline float pi0() const;
  inline void set_pi0(float value);

  // @@protoc_insertion_point(class_scope:gsbn.ProjParam)
 private:
  inline void set_has_src_pop();
  inline void clear_has_src_pop();
  inline void set_has_dest_pop();
  inline void clear_has_dest_pop();
  inline void set_has_tauzi();
  inline void clear_has_tauzi();
  inline void set_has_tauzj();
  inline void clear_has_tauzj();
  inline void set_has_taue();
  inline void clear_has_taue();
  inline void set_has_taup();
  inline void clear_has_taup();
  inline void set_has_maxfq();
  inline void clear_has_maxfq();
  inline void set_has_bgain();
  inline void clear_has_bgain();
  inline void set_has_wgain();
  inline void clear_has_wgain();
  inline void set_has_pi0();
  inline void clear_has_pi0();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 src_pop_;
  ::google::protobuf::uint32 dest_pop_;
  float tauzi_;
  float tauzj_;
  float taue_;
  float taup_;
  float maxfq_;
  float bgain_;
  float wgain_;
  float pi0_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static ProjParam* default_instance_;
};
// -------------------------------------------------------------------

class SolverState : public ::google::protobuf::Message {
 public:
  SolverState();
  virtual ~SolverState();

  SolverState(const SolverState& from);

  inline SolverState& operator=(const SolverState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SolverState& default_instance();

  void Swap(SolverState* other);

  // implements Message ----------------------------------------------

  SolverState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SolverState& from);
  void MergeFrom(const SolverState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline float timestamp() const;
  inline void set_timestamp(float value);

  // repeated .gsbn.TableState table_state = 2;
  inline int table_state_size() const;
  inline void clear_table_state();
  static const int kTableStateFieldNumber = 2;
  inline const ::gsbn::TableState& table_state(int index) const;
  inline ::gsbn::TableState* mutable_table_state(int index);
  inline ::gsbn::TableState* add_table_state();
  inline const ::google::protobuf::RepeatedPtrField< ::gsbn::TableState >&
      table_state() const;
  inline ::google::protobuf::RepeatedPtrField< ::gsbn::TableState >*
      mutable_table_state();

  // @@protoc_insertion_point(class_scope:gsbn.SolverState)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::gsbn::TableState > table_state_;
  float timestamp_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static SolverState* default_instance_;
};
// -------------------------------------------------------------------

class TableState : public ::google::protobuf::Message {
 public:
  TableState();
  virtual ~TableState();

  TableState(const TableState& from);

  inline TableState& operator=(const TableState& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TableState& default_instance();

  void Swap(TableState* other);

  // implements Message ----------------------------------------------

  TableState* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TableState& from);
  void MergeFrom(const TableState& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required bytes desc = 2;
  inline bool has_desc() const;
  inline void clear_desc();
  static const int kDescFieldNumber = 2;
  inline const ::std::string& desc() const;
  inline void set_desc(const ::std::string& value);
  inline void set_desc(const char* value);
  inline void set_desc(const void* value, size_t size);
  inline ::std::string* mutable_desc();
  inline ::std::string* release_desc();
  inline void set_allocated_desc(::std::string* desc);

  // required bytes data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // @@protoc_insertion_point(class_scope:gsbn.TableState)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_desc();
  inline void clear_has_desc();
  inline void set_has_data();
  inline void clear_has_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* desc_;
  ::std::string* data_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static TableState* default_instance_;
};
// -------------------------------------------------------------------

class StimRawData : public ::google::protobuf::Message {
 public:
  StimRawData();
  virtual ~StimRawData();

  StimRawData(const StimRawData& from);

  inline StimRawData& operator=(const StimRawData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StimRawData& default_instance();

  void Swap(StimRawData* other);

  // implements Message ----------------------------------------------

  StimRawData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StimRawData& from);
  void MergeFrom(const StimRawData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 rows = 1;
  inline bool has_rows() const;
  inline void clear_rows();
  static const int kRowsFieldNumber = 1;
  inline ::google::protobuf::uint32 rows() const;
  inline void set_rows(::google::protobuf::uint32 value);

  // required uint32 cols = 2;
  inline bool has_cols() const;
  inline void clear_cols();
  static const int kColsFieldNumber = 2;
  inline ::google::protobuf::uint32 cols() const;
  inline void set_cols(::google::protobuf::uint32 value);

  // repeated float data = 3 [packed = true];
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline float data(int index) const;
  inline void set_data(int index, float value);
  inline void add_data(float value);
  inline const ::google::protobuf::RepeatedField< float >&
      data() const;
  inline ::google::protobuf::RepeatedField< float >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:gsbn.StimRawData)
 private:
  inline void set_has_rows();
  inline void clear_has_rows();
  inline void set_has_cols();
  inline void clear_has_cols();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 rows_;
  ::google::protobuf::uint32 cols_;
  ::google::protobuf::RepeatedField< float > data_;
  mutable int _data_cached_byte_size_;
  friend void  protobuf_AddDesc_gsbn_2eproto();
  friend void protobuf_AssignDesc_gsbn_2eproto();
  friend void protobuf_ShutdownFile_gsbn_2eproto();

  void InitAsDefaultInstance();
  static StimRawData* default_instance_;
};
// ===================================================================


// ===================================================================

// SolverParam

// required .gsbn.GenParam gen_param = 1;
inline bool SolverParam::has_gen_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SolverParam::set_has_gen_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SolverParam::clear_has_gen_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SolverParam::clear_gen_param() {
  if (gen_param_ != NULL) gen_param_->::gsbn::GenParam::Clear();
  clear_has_gen_param();
}
inline const ::gsbn::GenParam& SolverParam::gen_param() const {
  // @@protoc_insertion_point(field_get:gsbn.SolverParam.gen_param)
  return gen_param_ != NULL ? *gen_param_ : *default_instance_->gen_param_;
}
inline ::gsbn::GenParam* SolverParam::mutable_gen_param() {
  set_has_gen_param();
  if (gen_param_ == NULL) gen_param_ = new ::gsbn::GenParam;
  // @@protoc_insertion_point(field_mutable:gsbn.SolverParam.gen_param)
  return gen_param_;
}
inline ::gsbn::GenParam* SolverParam::release_gen_param() {
  clear_has_gen_param();
  ::gsbn::GenParam* temp = gen_param_;
  gen_param_ = NULL;
  return temp;
}
inline void SolverParam::set_allocated_gen_param(::gsbn::GenParam* gen_param) {
  delete gen_param_;
  gen_param_ = gen_param;
  if (gen_param) {
    set_has_gen_param();
  } else {
    clear_has_gen_param();
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.SolverParam.gen_param)
}

// required .gsbn.NetParam net_param = 2;
inline bool SolverParam::has_net_param() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SolverParam::set_has_net_param() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SolverParam::clear_has_net_param() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SolverParam::clear_net_param() {
  if (net_param_ != NULL) net_param_->::gsbn::NetParam::Clear();
  clear_has_net_param();
}
inline const ::gsbn::NetParam& SolverParam::net_param() const {
  // @@protoc_insertion_point(field_get:gsbn.SolverParam.net_param)
  return net_param_ != NULL ? *net_param_ : *default_instance_->net_param_;
}
inline ::gsbn::NetParam* SolverParam::mutable_net_param() {
  set_has_net_param();
  if (net_param_ == NULL) net_param_ = new ::gsbn::NetParam;
  // @@protoc_insertion_point(field_mutable:gsbn.SolverParam.net_param)
  return net_param_;
}
inline ::gsbn::NetParam* SolverParam::release_net_param() {
  clear_has_net_param();
  ::gsbn::NetParam* temp = net_param_;
  net_param_ = NULL;
  return temp;
}
inline void SolverParam::set_allocated_net_param(::gsbn::NetParam* net_param) {
  delete net_param_;
  net_param_ = net_param;
  if (net_param) {
    set_has_net_param();
  } else {
    clear_has_net_param();
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.SolverParam.net_param)
}

// -------------------------------------------------------------------

// GenParam

// optional string stim_file = 1;
inline bool GenParam::has_stim_file() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GenParam::set_has_stim_file() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GenParam::clear_has_stim_file() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GenParam::clear_stim_file() {
  if (stim_file_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    stim_file_->clear();
  }
  clear_has_stim_file();
}
inline const ::std::string& GenParam::stim_file() const {
  // @@protoc_insertion_point(field_get:gsbn.GenParam.stim_file)
  return *stim_file_;
}
inline void GenParam::set_stim_file(const ::std::string& value) {
  set_has_stim_file();
  if (stim_file_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    stim_file_ = new ::std::string;
  }
  stim_file_->assign(value);
  // @@protoc_insertion_point(field_set:gsbn.GenParam.stim_file)
}
inline void GenParam::set_stim_file(const char* value) {
  set_has_stim_file();
  if (stim_file_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    stim_file_ = new ::std::string;
  }
  stim_file_->assign(value);
  // @@protoc_insertion_point(field_set_char:gsbn.GenParam.stim_file)
}
inline void GenParam::set_stim_file(const char* value, size_t size) {
  set_has_stim_file();
  if (stim_file_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    stim_file_ = new ::std::string;
  }
  stim_file_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gsbn.GenParam.stim_file)
}
inline ::std::string* GenParam::mutable_stim_file() {
  set_has_stim_file();
  if (stim_file_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    stim_file_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gsbn.GenParam.stim_file)
  return stim_file_;
}
inline ::std::string* GenParam::release_stim_file() {
  clear_has_stim_file();
  if (stim_file_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = stim_file_;
    stim_file_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void GenParam::set_allocated_stim_file(::std::string* stim_file) {
  if (stim_file_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete stim_file_;
  }
  if (stim_file) {
    set_has_stim_file();
    stim_file_ = stim_file;
  } else {
    clear_has_stim_file();
    stim_file_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.GenParam.stim_file)
}

// required float dt = 2;
inline bool GenParam::has_dt() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GenParam::set_has_dt() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GenParam::clear_has_dt() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GenParam::clear_dt() {
  dt_ = 0;
  clear_has_dt();
}
inline float GenParam::dt() const {
  // @@protoc_insertion_point(field_get:gsbn.GenParam.dt)
  return dt_;
}
inline void GenParam::set_dt(float value) {
  set_has_dt();
  dt_ = value;
  // @@protoc_insertion_point(field_set:gsbn.GenParam.dt)
}

// repeated .gsbn.ModeParam mode_param = 3;
inline int GenParam::mode_param_size() const {
  return mode_param_.size();
}
inline void GenParam::clear_mode_param() {
  mode_param_.Clear();
}
inline const ::gsbn::ModeParam& GenParam::mode_param(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.GenParam.mode_param)
  return mode_param_.Get(index);
}
inline ::gsbn::ModeParam* GenParam::mutable_mode_param(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.GenParam.mode_param)
  return mode_param_.Mutable(index);
}
inline ::gsbn::ModeParam* GenParam::add_mode_param() {
  // @@protoc_insertion_point(field_add:gsbn.GenParam.mode_param)
  return mode_param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::ModeParam >&
GenParam::mode_param() const {
  // @@protoc_insertion_point(field_list:gsbn.GenParam.mode_param)
  return mode_param_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::ModeParam >*
GenParam::mutable_mode_param() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.GenParam.mode_param)
  return &mode_param_;
}

// -------------------------------------------------------------------

// ModeParam

// required float begin_time = 1;
inline bool ModeParam::has_begin_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModeParam::set_has_begin_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModeParam::clear_has_begin_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModeParam::clear_begin_time() {
  begin_time_ = 0;
  clear_has_begin_time();
}
inline float ModeParam::begin_time() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.begin_time)
  return begin_time_;
}
inline void ModeParam::set_begin_time(float value) {
  set_has_begin_time();
  begin_time_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.begin_time)
}

// required float end_time = 2;
inline bool ModeParam::has_end_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ModeParam::set_has_end_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ModeParam::clear_has_end_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ModeParam::clear_end_time() {
  end_time_ = 0;
  clear_has_end_time();
}
inline float ModeParam::end_time() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.end_time)
  return end_time_;
}
inline void ModeParam::set_end_time(float value) {
  set_has_end_time();
  end_time_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.end_time)
}

// optional float prn = 3 [default = 1];
inline bool ModeParam::has_prn() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ModeParam::set_has_prn() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ModeParam::clear_has_prn() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ModeParam::clear_prn() {
  prn_ = 1;
  clear_has_prn();
}
inline float ModeParam::prn() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.prn)
  return prn_;
}
inline void ModeParam::set_prn(float value) {
  set_has_prn();
  prn_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.prn)
}

// optional float gain_mask = 4 [default = 1];
inline bool ModeParam::has_gain_mask() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ModeParam::set_has_gain_mask() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ModeParam::clear_has_gain_mask() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ModeParam::clear_gain_mask() {
  gain_mask_ = 1;
  clear_has_gain_mask();
}
inline float ModeParam::gain_mask() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.gain_mask)
  return gain_mask_;
}
inline void ModeParam::set_gain_mask(float value) {
  set_has_gain_mask();
  gain_mask_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.gain_mask)
}

// optional uint32 plasticity = 5 [default = 1];
inline bool ModeParam::has_plasticity() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ModeParam::set_has_plasticity() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ModeParam::clear_has_plasticity() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ModeParam::clear_plasticity() {
  plasticity_ = 1u;
  clear_has_plasticity();
}
inline ::google::protobuf::uint32 ModeParam::plasticity() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.plasticity)
  return plasticity_;
}
inline void ModeParam::set_plasticity(::google::protobuf::uint32 value) {
  set_has_plasticity();
  plasticity_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.plasticity)
}

// optional uint32 stim_index = 6 [default = 0];
inline bool ModeParam::has_stim_index() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ModeParam::set_has_stim_index() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ModeParam::clear_has_stim_index() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ModeParam::clear_stim_index() {
  stim_index_ = 0u;
  clear_has_stim_index();
}
inline ::google::protobuf::uint32 ModeParam::stim_index() const {
  // @@protoc_insertion_point(field_get:gsbn.ModeParam.stim_index)
  return stim_index_;
}
inline void ModeParam::set_stim_index(::google::protobuf::uint32 value) {
  set_has_stim_index();
  stim_index_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ModeParam.stim_index)
}

// -------------------------------------------------------------------

// NetParam

// repeated .gsbn.PopParam pop_param = 1;
inline int NetParam::pop_param_size() const {
  return pop_param_.size();
}
inline void NetParam::clear_pop_param() {
  pop_param_.Clear();
}
inline const ::gsbn::PopParam& NetParam::pop_param(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.NetParam.pop_param)
  return pop_param_.Get(index);
}
inline ::gsbn::PopParam* NetParam::mutable_pop_param(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.NetParam.pop_param)
  return pop_param_.Mutable(index);
}
inline ::gsbn::PopParam* NetParam::add_pop_param() {
  // @@protoc_insertion_point(field_add:gsbn.NetParam.pop_param)
  return pop_param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::PopParam >&
NetParam::pop_param() const {
  // @@protoc_insertion_point(field_list:gsbn.NetParam.pop_param)
  return pop_param_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::PopParam >*
NetParam::mutable_pop_param() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.NetParam.pop_param)
  return &pop_param_;
}

// repeated .gsbn.ProjParam proj_param = 2;
inline int NetParam::proj_param_size() const {
  return proj_param_.size();
}
inline void NetParam::clear_proj_param() {
  proj_param_.Clear();
}
inline const ::gsbn::ProjParam& NetParam::proj_param(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.NetParam.proj_param)
  return proj_param_.Get(index);
}
inline ::gsbn::ProjParam* NetParam::mutable_proj_param(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.NetParam.proj_param)
  return proj_param_.Mutable(index);
}
inline ::gsbn::ProjParam* NetParam::add_proj_param() {
  // @@protoc_insertion_point(field_add:gsbn.NetParam.proj_param)
  return proj_param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::ProjParam >&
NetParam::proj_param() const {
  // @@protoc_insertion_point(field_list:gsbn.NetParam.proj_param)
  return proj_param_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::ProjParam >*
NetParam::mutable_proj_param() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.NetParam.proj_param)
  return &proj_param_;
}

// -------------------------------------------------------------------

// PopParam

// required uint32 pop_num = 1;
inline bool PopParam::has_pop_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PopParam::set_has_pop_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PopParam::clear_has_pop_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PopParam::clear_pop_num() {
  pop_num_ = 0u;
  clear_has_pop_num();
}
inline ::google::protobuf::uint32 PopParam::pop_num() const {
  // @@protoc_insertion_point(field_get:gsbn.PopParam.pop_num)
  return pop_num_;
}
inline void PopParam::set_pop_num(::google::protobuf::uint32 value) {
  set_has_pop_num();
  pop_num_ = value;
  // @@protoc_insertion_point(field_set:gsbn.PopParam.pop_num)
}

// repeated .gsbn.HcuParam hcu_param = 2;
inline int PopParam::hcu_param_size() const {
  return hcu_param_.size();
}
inline void PopParam::clear_hcu_param() {
  hcu_param_.Clear();
}
inline const ::gsbn::HcuParam& PopParam::hcu_param(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.PopParam.hcu_param)
  return hcu_param_.Get(index);
}
inline ::gsbn::HcuParam* PopParam::mutable_hcu_param(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.PopParam.hcu_param)
  return hcu_param_.Mutable(index);
}
inline ::gsbn::HcuParam* PopParam::add_hcu_param() {
  // @@protoc_insertion_point(field_add:gsbn.PopParam.hcu_param)
  return hcu_param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::HcuParam >&
PopParam::hcu_param() const {
  // @@protoc_insertion_point(field_list:gsbn.PopParam.hcu_param)
  return hcu_param_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::HcuParam >*
PopParam::mutable_hcu_param() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.PopParam.hcu_param)
  return &hcu_param_;
}

// -------------------------------------------------------------------

// HcuParam

// required uint32 hcu_num = 1;
inline bool HcuParam::has_hcu_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HcuParam::set_has_hcu_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HcuParam::clear_has_hcu_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HcuParam::clear_hcu_num() {
  hcu_num_ = 0u;
  clear_has_hcu_num();
}
inline ::google::protobuf::uint32 HcuParam::hcu_num() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.hcu_num)
  return hcu_num_;
}
inline void HcuParam::set_hcu_num(::google::protobuf::uint32 value) {
  set_has_hcu_num();
  hcu_num_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.hcu_num)
}

// required uint32 slot_num = 2;
inline bool HcuParam::has_slot_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HcuParam::set_has_slot_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HcuParam::clear_has_slot_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HcuParam::clear_slot_num() {
  slot_num_ = 0u;
  clear_has_slot_num();
}
inline ::google::protobuf::uint32 HcuParam::slot_num() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.slot_num)
  return slot_num_;
}
inline void HcuParam::set_slot_num(::google::protobuf::uint32 value) {
  set_has_slot_num();
  slot_num_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.slot_num)
}

// repeated .gsbn.McuParam mcu_param = 3;
inline int HcuParam::mcu_param_size() const {
  return mcu_param_.size();
}
inline void HcuParam::clear_mcu_param() {
  mcu_param_.Clear();
}
inline const ::gsbn::McuParam& HcuParam::mcu_param(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.mcu_param)
  return mcu_param_.Get(index);
}
inline ::gsbn::McuParam* HcuParam::mutable_mcu_param(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.HcuParam.mcu_param)
  return mcu_param_.Mutable(index);
}
inline ::gsbn::McuParam* HcuParam::add_mcu_param() {
  // @@protoc_insertion_point(field_add:gsbn.HcuParam.mcu_param)
  return mcu_param_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::McuParam >&
HcuParam::mcu_param() const {
  // @@protoc_insertion_point(field_list:gsbn.HcuParam.mcu_param)
  return mcu_param_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::McuParam >*
HcuParam::mutable_mcu_param() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.HcuParam.mcu_param)
  return &mcu_param_;
}

// required float taum = 4;
inline bool HcuParam::has_taum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HcuParam::set_has_taum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HcuParam::clear_has_taum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HcuParam::clear_taum() {
  taum_ = 0;
  clear_has_taum();
}
inline float HcuParam::taum() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.taum)
  return taum_;
}
inline void HcuParam::set_taum(float value) {
  set_has_taum();
  taum_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.taum)
}

// required float wtagain = 5;
inline bool HcuParam::has_wtagain() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HcuParam::set_has_wtagain() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HcuParam::clear_has_wtagain() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HcuParam::clear_wtagain() {
  wtagain_ = 0;
  clear_has_wtagain();
}
inline float HcuParam::wtagain() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.wtagain)
  return wtagain_;
}
inline void HcuParam::set_wtagain(float value) {
  set_has_wtagain();
  wtagain_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.wtagain)
}

// required float maxfq = 6;
inline bool HcuParam::has_maxfq() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void HcuParam::set_has_maxfq() {
  _has_bits_[0] |= 0x00000020u;
}
inline void HcuParam::clear_has_maxfq() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void HcuParam::clear_maxfq() {
  maxfq_ = 0;
  clear_has_maxfq();
}
inline float HcuParam::maxfq() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.maxfq)
  return maxfq_;
}
inline void HcuParam::set_maxfq(float value) {
  set_has_maxfq();
  maxfq_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.maxfq)
}

// optional float igain = 7 [default = 1];
inline bool HcuParam::has_igain() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void HcuParam::set_has_igain() {
  _has_bits_[0] |= 0x00000040u;
}
inline void HcuParam::clear_has_igain() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void HcuParam::clear_igain() {
  igain_ = 1;
  clear_has_igain();
}
inline float HcuParam::igain() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.igain)
  return igain_;
}
inline void HcuParam::set_igain(float value) {
  set_has_igain();
  igain_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.igain)
}

// optional float wgain = 8 [default = 1];
inline bool HcuParam::has_wgain() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void HcuParam::set_has_wgain() {
  _has_bits_[0] |= 0x00000080u;
}
inline void HcuParam::clear_has_wgain() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void HcuParam::clear_wgain() {
  wgain_ = 1;
  clear_has_wgain();
}
inline float HcuParam::wgain() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.wgain)
  return wgain_;
}
inline void HcuParam::set_wgain(float value) {
  set_has_wgain();
  wgain_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.wgain)
}

// optional float snoise = 9 [default = 0];
inline bool HcuParam::has_snoise() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void HcuParam::set_has_snoise() {
  _has_bits_[0] |= 0x00000100u;
}
inline void HcuParam::clear_has_snoise() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void HcuParam::clear_snoise() {
  snoise_ = 0;
  clear_has_snoise();
}
inline float HcuParam::snoise() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.snoise)
  return snoise_;
}
inline void HcuParam::set_snoise(float value) {
  set_has_snoise();
  snoise_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.snoise)
}

// optional float lgbias = 10 [default = 0];
inline bool HcuParam::has_lgbias() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void HcuParam::set_has_lgbias() {
  _has_bits_[0] |= 0x00000200u;
}
inline void HcuParam::clear_has_lgbias() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void HcuParam::clear_lgbias() {
  lgbias_ = 0;
  clear_has_lgbias();
}
inline float HcuParam::lgbias() const {
  // @@protoc_insertion_point(field_get:gsbn.HcuParam.lgbias)
  return lgbias_;
}
inline void HcuParam::set_lgbias(float value) {
  set_has_lgbias();
  lgbias_ = value;
  // @@protoc_insertion_point(field_set:gsbn.HcuParam.lgbias)
}

// -------------------------------------------------------------------

// McuParam

// required uint32 mcu_num = 1;
inline bool McuParam::has_mcu_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void McuParam::set_has_mcu_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void McuParam::clear_has_mcu_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void McuParam::clear_mcu_num() {
  mcu_num_ = 0u;
  clear_has_mcu_num();
}
inline ::google::protobuf::uint32 McuParam::mcu_num() const {
  // @@protoc_insertion_point(field_get:gsbn.McuParam.mcu_num)
  return mcu_num_;
}
inline void McuParam::set_mcu_num(::google::protobuf::uint32 value) {
  set_has_mcu_num();
  mcu_num_ = value;
  // @@protoc_insertion_point(field_set:gsbn.McuParam.mcu_num)
}

// required uint32 fanout_num = 2;
inline bool McuParam::has_fanout_num() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void McuParam::set_has_fanout_num() {
  _has_bits_[0] |= 0x00000002u;
}
inline void McuParam::clear_has_fanout_num() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void McuParam::clear_fanout_num() {
  fanout_num_ = 0u;
  clear_has_fanout_num();
}
inline ::google::protobuf::uint32 McuParam::fanout_num() const {
  // @@protoc_insertion_point(field_get:gsbn.McuParam.fanout_num)
  return fanout_num_;
}
inline void McuParam::set_fanout_num(::google::protobuf::uint32 value) {
  set_has_fanout_num();
  fanout_num_ = value;
  // @@protoc_insertion_point(field_set:gsbn.McuParam.fanout_num)
}

// -------------------------------------------------------------------

// ProjParam

// required uint32 src_pop = 1;
inline bool ProjParam::has_src_pop() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProjParam::set_has_src_pop() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProjParam::clear_has_src_pop() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProjParam::clear_src_pop() {
  src_pop_ = 0u;
  clear_has_src_pop();
}
inline ::google::protobuf::uint32 ProjParam::src_pop() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.src_pop)
  return src_pop_;
}
inline void ProjParam::set_src_pop(::google::protobuf::uint32 value) {
  set_has_src_pop();
  src_pop_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.src_pop)
}

// required uint32 dest_pop = 2;
inline bool ProjParam::has_dest_pop() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProjParam::set_has_dest_pop() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProjParam::clear_has_dest_pop() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProjParam::clear_dest_pop() {
  dest_pop_ = 0u;
  clear_has_dest_pop();
}
inline ::google::protobuf::uint32 ProjParam::dest_pop() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.dest_pop)
  return dest_pop_;
}
inline void ProjParam::set_dest_pop(::google::protobuf::uint32 value) {
  set_has_dest_pop();
  dest_pop_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.dest_pop)
}

// required float tauzi = 3;
inline bool ProjParam::has_tauzi() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ProjParam::set_has_tauzi() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ProjParam::clear_has_tauzi() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ProjParam::clear_tauzi() {
  tauzi_ = 0;
  clear_has_tauzi();
}
inline float ProjParam::tauzi() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.tauzi)
  return tauzi_;
}
inline void ProjParam::set_tauzi(float value) {
  set_has_tauzi();
  tauzi_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.tauzi)
}

// required float tauzj = 4;
inline bool ProjParam::has_tauzj() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ProjParam::set_has_tauzj() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ProjParam::clear_has_tauzj() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ProjParam::clear_tauzj() {
  tauzj_ = 0;
  clear_has_tauzj();
}
inline float ProjParam::tauzj() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.tauzj)
  return tauzj_;
}
inline void ProjParam::set_tauzj(float value) {
  set_has_tauzj();
  tauzj_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.tauzj)
}

// required float taue = 5;
inline bool ProjParam::has_taue() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void ProjParam::set_has_taue() {
  _has_bits_[0] |= 0x00000010u;
}
inline void ProjParam::clear_has_taue() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void ProjParam::clear_taue() {
  taue_ = 0;
  clear_has_taue();
}
inline float ProjParam::taue() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.taue)
  return taue_;
}
inline void ProjParam::set_taue(float value) {
  set_has_taue();
  taue_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.taue)
}

// required float taup = 6;
inline bool ProjParam::has_taup() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void ProjParam::set_has_taup() {
  _has_bits_[0] |= 0x00000020u;
}
inline void ProjParam::clear_has_taup() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void ProjParam::clear_taup() {
  taup_ = 0;
  clear_has_taup();
}
inline float ProjParam::taup() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.taup)
  return taup_;
}
inline void ProjParam::set_taup(float value) {
  set_has_taup();
  taup_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.taup)
}

// required float maxfq = 7;
inline bool ProjParam::has_maxfq() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void ProjParam::set_has_maxfq() {
  _has_bits_[0] |= 0x00000040u;
}
inline void ProjParam::clear_has_maxfq() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void ProjParam::clear_maxfq() {
  maxfq_ = 0;
  clear_has_maxfq();
}
inline float ProjParam::maxfq() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.maxfq)
  return maxfq_;
}
inline void ProjParam::set_maxfq(float value) {
  set_has_maxfq();
  maxfq_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.maxfq)
}

// optional float bgain = 8 [default = 0];
inline bool ProjParam::has_bgain() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void ProjParam::set_has_bgain() {
  _has_bits_[0] |= 0x00000080u;
}
inline void ProjParam::clear_has_bgain() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void ProjParam::clear_bgain() {
  bgain_ = 0;
  clear_has_bgain();
}
inline float ProjParam::bgain() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.bgain)
  return bgain_;
}
inline void ProjParam::set_bgain(float value) {
  set_has_bgain();
  bgain_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.bgain)
}

// optional float wgain = 9 [default = 0];
inline bool ProjParam::has_wgain() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void ProjParam::set_has_wgain() {
  _has_bits_[0] |= 0x00000100u;
}
inline void ProjParam::clear_has_wgain() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void ProjParam::clear_wgain() {
  wgain_ = 0;
  clear_has_wgain();
}
inline float ProjParam::wgain() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.wgain)
  return wgain_;
}
inline void ProjParam::set_wgain(float value) {
  set_has_wgain();
  wgain_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.wgain)
}

// optional float pi0 = 10 [default = 0];
inline bool ProjParam::has_pi0() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void ProjParam::set_has_pi0() {
  _has_bits_[0] |= 0x00000200u;
}
inline void ProjParam::clear_has_pi0() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void ProjParam::clear_pi0() {
  pi0_ = 0;
  clear_has_pi0();
}
inline float ProjParam::pi0() const {
  // @@protoc_insertion_point(field_get:gsbn.ProjParam.pi0)
  return pi0_;
}
inline void ProjParam::set_pi0(float value) {
  set_has_pi0();
  pi0_ = value;
  // @@protoc_insertion_point(field_set:gsbn.ProjParam.pi0)
}

// -------------------------------------------------------------------

// SolverState

// required float timestamp = 1;
inline bool SolverState::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SolverState::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SolverState::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SolverState::clear_timestamp() {
  timestamp_ = 0;
  clear_has_timestamp();
}
inline float SolverState::timestamp() const {
  // @@protoc_insertion_point(field_get:gsbn.SolverState.timestamp)
  return timestamp_;
}
inline void SolverState::set_timestamp(float value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:gsbn.SolverState.timestamp)
}

// repeated .gsbn.TableState table_state = 2;
inline int SolverState::table_state_size() const {
  return table_state_.size();
}
inline void SolverState::clear_table_state() {
  table_state_.Clear();
}
inline const ::gsbn::TableState& SolverState::table_state(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.SolverState.table_state)
  return table_state_.Get(index);
}
inline ::gsbn::TableState* SolverState::mutable_table_state(int index) {
  // @@protoc_insertion_point(field_mutable:gsbn.SolverState.table_state)
  return table_state_.Mutable(index);
}
inline ::gsbn::TableState* SolverState::add_table_state() {
  // @@protoc_insertion_point(field_add:gsbn.SolverState.table_state)
  return table_state_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::gsbn::TableState >&
SolverState::table_state() const {
  // @@protoc_insertion_point(field_list:gsbn.SolverState.table_state)
  return table_state_;
}
inline ::google::protobuf::RepeatedPtrField< ::gsbn::TableState >*
SolverState::mutable_table_state() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.SolverState.table_state)
  return &table_state_;
}

// -------------------------------------------------------------------

// TableState

// required string name = 1;
inline bool TableState::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TableState::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TableState::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TableState::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& TableState::name() const {
  // @@protoc_insertion_point(field_get:gsbn.TableState.name)
  return *name_;
}
inline void TableState::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:gsbn.TableState.name)
}
inline void TableState::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:gsbn.TableState.name)
}
inline void TableState::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gsbn.TableState.name)
}
inline ::std::string* TableState::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gsbn.TableState.name)
  return name_;
}
inline ::std::string* TableState::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TableState::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.TableState.name)
}

// required bytes desc = 2;
inline bool TableState::has_desc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TableState::set_has_desc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TableState::clear_has_desc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TableState::clear_desc() {
  if (desc_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_->clear();
  }
  clear_has_desc();
}
inline const ::std::string& TableState::desc() const {
  // @@protoc_insertion_point(field_get:gsbn.TableState.desc)
  return *desc_;
}
inline void TableState::set_desc(const ::std::string& value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
  // @@protoc_insertion_point(field_set:gsbn.TableState.desc)
}
inline void TableState::set_desc(const char* value) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(value);
  // @@protoc_insertion_point(field_set_char:gsbn.TableState.desc)
}
inline void TableState::set_desc(const void* value, size_t size) {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  desc_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gsbn.TableState.desc)
}
inline ::std::string* TableState::mutable_desc() {
  set_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    desc_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gsbn.TableState.desc)
  return desc_;
}
inline ::std::string* TableState::release_desc() {
  clear_has_desc();
  if (desc_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = desc_;
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TableState::set_allocated_desc(::std::string* desc) {
  if (desc_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete desc_;
  }
  if (desc) {
    set_has_desc();
    desc_ = desc;
  } else {
    clear_has_desc();
    desc_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.TableState.desc)
}

// required bytes data = 3;
inline bool TableState::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TableState::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TableState::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TableState::clear_data() {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& TableState::data() const {
  // @@protoc_insertion_point(field_get:gsbn.TableState.data)
  return *data_;
}
inline void TableState::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set:gsbn.TableState.data)
}
inline void TableState::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(value);
  // @@protoc_insertion_point(field_set_char:gsbn.TableState.data)
}
inline void TableState::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:gsbn.TableState.data)
}
inline ::std::string* TableState::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    data_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:gsbn.TableState.data)
  return data_;
}
inline ::std::string* TableState::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void TableState::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:gsbn.TableState.data)
}

// -------------------------------------------------------------------

// StimRawData

// required uint32 rows = 1;
inline bool StimRawData::has_rows() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StimRawData::set_has_rows() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StimRawData::clear_has_rows() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StimRawData::clear_rows() {
  rows_ = 0u;
  clear_has_rows();
}
inline ::google::protobuf::uint32 StimRawData::rows() const {
  // @@protoc_insertion_point(field_get:gsbn.StimRawData.rows)
  return rows_;
}
inline void StimRawData::set_rows(::google::protobuf::uint32 value) {
  set_has_rows();
  rows_ = value;
  // @@protoc_insertion_point(field_set:gsbn.StimRawData.rows)
}

// required uint32 cols = 2;
inline bool StimRawData::has_cols() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StimRawData::set_has_cols() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StimRawData::clear_has_cols() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StimRawData::clear_cols() {
  cols_ = 0u;
  clear_has_cols();
}
inline ::google::protobuf::uint32 StimRawData::cols() const {
  // @@protoc_insertion_point(field_get:gsbn.StimRawData.cols)
  return cols_;
}
inline void StimRawData::set_cols(::google::protobuf::uint32 value) {
  set_has_cols();
  cols_ = value;
  // @@protoc_insertion_point(field_set:gsbn.StimRawData.cols)
}

// repeated float data = 3 [packed = true];
inline int StimRawData::data_size() const {
  return data_.size();
}
inline void StimRawData::clear_data() {
  data_.Clear();
}
inline float StimRawData::data(int index) const {
  // @@protoc_insertion_point(field_get:gsbn.StimRawData.data)
  return data_.Get(index);
}
inline void StimRawData::set_data(int index, float value) {
  data_.Set(index, value);
  // @@protoc_insertion_point(field_set:gsbn.StimRawData.data)
}
inline void StimRawData::add_data(float value) {
  data_.Add(value);
  // @@protoc_insertion_point(field_add:gsbn.StimRawData.data)
}
inline const ::google::protobuf::RepeatedField< float >&
StimRawData::data() const {
  // @@protoc_insertion_point(field_list:gsbn.StimRawData.data)
  return data_;
}
inline ::google::protobuf::RepeatedField< float >*
StimRawData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:gsbn.StimRawData.data)
  return &data_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gsbn

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gsbn_2eproto__INCLUDED
